version: "3.9"

services:
  booking-postgres:
    image: postgres:16
    container_name: booking-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking
    ports:
      - "5434:5432" 
    volumes:
      - booking-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d booking"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  booking-data:
